### ISSUE TITLE
Error running semi_labelme

### ISSUE THREAD

**Issue by tgmorais** [wongsinglam/semi_labelme#1]
I am getting the following error when I try run "semi_labelme". The installation when smoothly, but I can´t run the app.

```
(semi_labelme) C:\Semi_Labelme-master>semi_labelme
C:\Users\tmorais\Anaconda3\envs\semi_labelme\lib\site-packages\mmcv\__init__.py:21: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  'On January 1, 2023, MMCV will release v2.0.0, in which it will remove '
Traceback (most recent call last):
  File "C:\Users\tmorais\Anaconda3\envs\semi_labelme\Scripts\semi_labelme-script.py", line 33, in <module>
    sys.exit(load_entry_point('semi-labelme', 'console_scripts', 'semi_labelme')())
  File "C:\Users\tmorais\Anaconda3\envs\semi_labelme\Scripts\semi_labelme-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\tmorais\Anaconda3\envs\semi_labelme\lib\site-packages\importlib_metadata\__init__.py", line 208, in load
    module = import_module(match.group('module'))
  File "C:\Users\tmorais\Anaconda3\envs\semi_labelme\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\semi_labelme-master\semi_labelme\__main__.py", line 14, in <module>
    from semi_labelme.app import MainWindow
  File "c:\semi_labelme-master\semi_labelme\app.py", line 37, in <module>
    from mmdet.apis import init_detector, inference_detector
  File "C:\Users\tmorais\Anaconda3\envs\semi_labelme\lib\site-packages\mmdet\apis\__init__.py", line 2, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "C:\Users\tmorais\Anaconda3\envs\semi_labelme\lib\site-packages\mmdet\apis\inference.py", line 8, in <module>
    from mmcv.ops import RoIPool
  File "C:\Users\tmorais\Anaconda3\envs\semi_labelme\lib\site-packages\mmcv\ops\__init__.py", line 3, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "C:\Users\tmorais\Anaconda3\envs\semi_labelme\lib\site-packages\mmcv\ops\active_rotated_filter.py", line 12, in <module>
    ['active_rotated_filter_forward', 'active_rotated_filter_backward'])
  File "C:\Users\tmorais\Anaconda3\envs\semi_labelme\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "C:\Users\tmorais\Anaconda3\envs\semi_labelme\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed: The specified procedure could not be found.
```

**Comment by wongsinglam** [comment]
Hi,

This problem may be related to mmdetection. It has been updated several times since I developed this project. Please check the installation of [mmdetection](https://github.com/open-mmlab/mmdetection).

**Comment by wongsinglam** [comment]
> I am getting the following error when I try run "semi_labelme". The installation when smoothly, but I can´t run the app.
> 
> ```
> (semi_labelme) C:\Semi_Labelme-master>semi_labelme
> C:\Users\tmorais\Anaconda3\envs\semi_labelme\lib\site-packages\mmcv\__init__.py:21: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
>   'On January 1, 2023, MMCV will release v2.0.0, in which it will remove '
> Traceback (most recent call last):
>   File "C:\Users\tmorais\Anaconda3\envs\semi_labelme\Scripts\semi_labelme-script.py", line 33, in <module>
>     sys.exit(load_entry_point('semi-labelme', 'console_scripts', 'semi_labelme')())
>   File "C:\Users\tmorais\Anaconda3\envs\semi_labelme\Scripts\semi_labelme-script.py", line 25, in importlib_load_entry_point
>     return next(matches).load()
>   File "C:\Users\tmorais\Anaconda3\envs\semi_labelme\lib\site-packages\importlib_metadata\__init__.py", line 208, in load
>     module = import_module(match.group('module'))
>   File "C:\Users\tmorais\Anaconda3\envs\semi_labelme\lib\importlib\__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "c:\semi_labelme-master\semi_labelme\__main__.py", line 14, in <module>
>     from semi_labelme.app import MainWindow
>   File "c:\semi_labelme-master\semi_labelme\app.py", line 37, in <module>
>     from mmdet.apis import init_detector, inference_detector
>   File "C:\Users\tmorais\Anaconda3\envs\semi_labelme\lib\site-packages\mmdet\apis\__init__.py", line 2, in <module>
>     from .inference import (async_inference_detector, inference_detector,
>   File "C:\Users\tmorais\Anaconda3\envs\semi_labelme\lib\site-packages\mmdet\apis\inference.py", line 8, in <module>
>     from mmcv.ops import RoIPool
>   File "C:\Users\tmorais\Anaconda3\envs\semi_labelme\lib\site-packages\mmcv\ops\__init__.py", line 3, in <module>
>     from .active_rotated_filter import active_rotated_filter
>   File "C:\Users\tmorais\Anaconda3\envs\semi_labelme\lib\site-packages\mmcv\ops\active_rotated_filter.py", line 12, in <module>
>     ['active_rotated_filter_forward', 'active_rotated_filter_backward'])
>   File "C:\Users\tmorais\Anaconda3\envs\semi_labelme\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
>     ext = importlib.import_module('mmcv.' + name)
>   File "C:\Users\tmorais\Anaconda3\envs\semi_labelme\lib\importlib\__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
> ImportError: DLL load failed: The specified procedure could not be found.
> ```

Hi,

This problem may be related to mmdetection. It has been updated several times since I developed this project. Please check the installation of [mmdetection](https://github.com/open-mmlab/mmdetection).
